server:
  port: 8080

spring:
  application:
    name: library-management
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:h2:mem:lms
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}

